/** OMA analytics bridge v12.0.1 */
/**
 * TypeScript ↔ Analytics bridge.
 * Currently routes to TypeScript adapters (parity with JS baseline).
 * When WASM package is available, heavy paths switch to Rust core.
 *
 * Usage:
 *   import { analytics } from '@/bridge/analytics';
 *   const r = analytics.rsi(closes, 14);
 */

import * as indicators from '../adapters/indicators';
import type { Candle, MacdConfig, MacdResult, BollingerResult, StochResult, AdxResult, SRResult, BreakoutResult } from '../types';

export type AnalyticsBackend = 'typescript' | 'wasm' | 'auto';

let backend: AnalyticsBackend = 'typescript';
let wasmReady = false;

/** Attempt to load WASM core (optional). */
export async function initAnalytics(preferred: AnalyticsBackend = 'auto'): Promise<AnalyticsBackend> {
  if (preferred === 'typescript') {
    backend = 'typescript';
    return backend;
  }
  try {
    // Placeholder: when src/bridge/pkg is generated by wasm-bindgen
    // const wasm = await import('./pkg/oma_core.js');
    // await wasm.default();
    // wasmReady = true;
    // backend = 'wasm';
    backend = 'typescript';
  } catch {
    backend = 'typescript';
    wasmReady = false;
  }
  return backend;
}

export function getBackend(): AnalyticsBackend {
  return backend;
}

export function isWasmReady(): boolean {
  return wasmReady;
}

/** Unified analytics surface — always matches JS baseline numerically. */
export const analytics = {
  isNum: indicators.isNum,
  last: indicators.last,
  sma: indicators.sma,
  ema: indicators.ema,
  emaSeries: indicators.emaSeries,
  rsi: indicators.rsi,
  momentum: indicators.momentum,
  roc: indicators.roc,
  atr: indicators.atr,
  macd: (closes: (number | null | undefined)[] | null | undefined, cfg?: MacdConfig): MacdResult =>
    indicators.macd(closes, cfg as any),
  bollinger: indicators.bollinger as (
    closes: (number | null | undefined)[] | null | undefined,
    period?: number,
    mult?: number
  ) => BollingerResult,
  stochastic: indicators.stochastic as (
    candles: Candle[] | null | undefined,
    k?: number,
    d?: number
  ) => StochResult,
  adx: indicators.adx as (candles: Candle[] | null | undefined, period?: number) => AdxResult,
  supportResistance: indicators.supportResistance as (
    candles: Candle[] | null | undefined,
    lookback?: number
  ) => SRResult,
  volumeAnalysis: indicators.volumeAnalysis,
  detectBreakout: indicators.detectBreakout as (
    candles: Candle[] | null | undefined,
    lookback?: number
  ) => BreakoutResult,
  maxDrawdown: indicators.maxDrawdown,
  volatilityPct: indicators.volatilityPct,
  fibonacciLevels: indicators.fibonacciLevels,
};

export default analytics;
